name: Latest YouTube Videos
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-youtube:
    name: Update README with latest YouTube videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: basit/youtube-latest-videos-action@v1.1
        with:
          channel_id: "UC_LOli__Rr4BC7Ddupn6Tfw"
